### ISSUE TITLE
Is the Lsos too easy to cheat?

### ISSUE THREAD

**Issue by ljharb** [Lsos/lsos-js#1]
With both yarn and a future version of npm 7, users will be able to trivially alias any LSOS dependency to a similarly-behaving one that's a noop. Someone could also trivially write a tool that worked like `npx kill-lsos` that modified your package.json to add the override, in preinstall even, so folks wouldn't even need to maintain that override pattern over time.

Instead of that, or even if authors inline LSOS code into their package, a `patch-package` approach would trivially excise LSOS code from the graph without needing any forking, just adding a single copy-pasteable line to `postinstall` in package.json.

What's the benefit of an enforcement mechanism that's so easily and legally bypassed, versus no enforcement mechanism at all?

**Comment by brillout** [comment]
Hi @ljharb!

Thanks for opening this ticket, I'm always happy to discuss the details.

Yes, we are aware of this, and we are working on a tool to automatically inline the Lsos code into the source code of the Lsos project. We make random modifications to the inlined code making it harder to be founded and removed. At the beginning we make cheating purposely easy and, once a cheat is popular, we ship our anti-cheat, so that there are many cheats on the Google first result page that don't work anymore. We've got designs to make forking an Lsos project to circumvent the fee time consuming enough to not be worth it. Etc.

In the end, this is a cat-and-mouse game.

How many companies will go the extra mile to circumvent a mere 10$/month? Even if 90% of the companies will (very unlikely), that's still 10% paying the fee which is several orders of magnitude higher than the current donation rate of like 0.01%.

Some open source projects are so popular and loved, that many employees will want their company to pay the fee. All the startups I worked for in the past would have wanted to be "cool & hip" and would have paid a "cool Lsos fee". Communicating the Lsos as a lovely thing will be important down the line. Netflix is trivial to cheat, yet people love Netflix and don't even think of cheating it.

Even with the `onlyWarning` flag (= no enforcement), we expect the yield to be vastly higher than donations.

(I took the liberty of renaming the title of this ticket, I hope it's ok with you.)

**Comment by ljharb** [comment]
There wouldn't be "many cheats", though, there'd just be a single one that has version-appropriate, or heuristic-aware, approaches. Certainly there's a cat-and-mouse game, but unlike most fraud software, you have to publish to npm, and responsible developers will use `^` (allowing the lowest version to be targeted), or, things won't be frequently updated - meaning, the "cheaters" will always be significantly ahead of you.

I completely agree that some employees will want their company to pay; I completely agree that some companies will be willing to pay; this enforcement mechanism has no impact on that. What I expect will happen is that employees will want to get something working *first*, before asking for money, which requires they bypass the check, or use an alternative (which defeats the purpose).

Netflix is not an open source software project, and is simply not comparable in any way (and humans don't have the fiscal burdens or justification requirements of a company; companies have a legal fiduciary duty to themselves that humans don't).

**Comment by ljharb** [comment]
I also suspect that authors themselves will be *highly* unwilling to add runtime weight to their package. I maintain a significant percentage of the downloads off of npmjs.com, and I wouldn't burden my users in this way.

That also leads to a separate question: how would you enforce this in a package that's never invoked in node, only bundled and ran in the browser? Surely you wouldn't expect users' websites to make a request to verify a license key, nor would you want such a key transmitted down to the browser.

**Comment by brillout** [comment]
Yes, when a company pins a lower version of an Lsos project, then the anti-Lsos library will be ahead. But when the company will want to update the Lsos project to its latest version, then it is the Lsos library who is ahead. The goal of our anti-cheat measures is not to make it impossible to cheat but to make it unreliable/annoying enough. Keep in mind that we are speaking of like 10$/month per Lsos project; that's peanuts for larger companies.

Larger companies get a free-trial activation key. (Individuals and small projects don't need an activation key.)

The anti-cheat thing is actually not our biggest focus. We focus more on getting companies to want to pay the fee. We have couple of neat ideas in that area which will actually play a bigger role than our anti-cheats.

I agree that non-technical Netflix users don't cheat because they are not aware of how easy it is to bypass the Netflix fee. The thing is that even my technical friends who are aware of things like torrents don't cheat Netflix.

We are actually interested in leveraging copyright law (we've designed a license clause that brings larger companies to pay while keeping code forkable) but now is not the right time (most open source developers don't understand how copyright works).

Yes, I've seen that you maintain a lot of packages, which is super neat. I'm doing a bit of open source as well and I've felt how frustrating it is to love something but not being able to work full-time on it (which is what drives me and the Lsos).

The library is tiny and has no dependencies (runtime is ~100 LOC and postinstall script is ~1k LOC). Activation key verification is done offline by using asymmetric encryption.

**Comment by ljharb** [comment]
In this scenario, the company is the one cheating - why would they ever want to update it?

7 days is nowhere near enough time for a free trial - it takes *months* sometimes to get companies to spend money on software.

**Comment by brillout** [comment]
> In this scenario, the company is the one cheating - why would they ever want to update it?

For example a company that regularly updates its packages to ensure that the latest bugfixes and security patches are included in its build. Everytime the company does this, the Lsos lib is ahead of the anti-Lsos lib.

> 7 days is nowhere near enough

7 days is just the default and can be changed to however long the open source project deems appropriate. But you're right, the default should be higher.

**Comment by brillout** [comment]
We refined our anti-cheat strategy.

Every offline Software is crackable, it's impossible to avoid, no matter how much anti-cheat implemented. I've yet to see a popular offline Software that no reverse engineer has put the effort to crack.

From the user's perspective, any cracked Software is more and less equally easy to cheat.

The main selfish rational reason why companies don't like to use cracked Software is trust: it's difficult to trust the cracked version to not include malicious code.

To ensure this rational reason also applies to the Lsos, we will publish the anti-Lsos library anonymously ourselves, and make sure it is the most popular one. (Anonymously so that no one can be sure that we are the one behind the anti-Lsos library). We will ensure that enough people use it but we will also make sure that it's difficult enough to trust so that most won't want to use it. (For example by making the Npm/GitHub owner an unkown account with no popular repositories.) This gives us control over the cheat-rate. We will (obviously) never include malicious code in our anonymously maintained anti-Lsos lib but the users will not be able to know this.

We expect the cheat-rate to be in the same ballpark than other offline Software. Photoshop is cracked but successfull, Microsoft Office is cracked but successfull, etc. The Lsos should be no exception to the rule. Actually, if anything, the Lsos cheat-rate would be lower than average because the moral burden to cheat open source is higher than cheating Adobe or Microsoft.

**Comment by ljharb** [comment]
It's notable that all of the projects you just mentioned have migrated to being online subscription services rather than single-sale software with a license key.

**Comment by brillout** [comment]
Yes, it's an interesting evolution (and I can't wait to see Wasm evolving.).

Any web app with offline support will still be crackable though. It will be interesting to see whether companies will choose to add offline support despite exposing their Software to reverse engineers.

Anyways, offline Software don't have cheat-rates of >90% and we wouldn't know why the Lsos would be the exception to the rule.

If you can find a fundamental reason why the Lsos would have a substantially higher cheat-rate than classical offline Software, please let us know. That would help us a lot in our quest to bring financial sustainability to open source.

In the time being, I'm closing this ticket and mark it as resolved. (I'm re-renaming the ticket's title, I hope it's ok.) Thanks for opening this ticket, it helped us clarify our strategy!

Btw., worst case, we go for copyright law with something like the [Justice License](https://github.com/brillout/justice-license#readme). So far, we don't think we need copyright and the Lsos library should be enough.
